### ISSUE TITLE
Research: Auto-API documentation for express 

### ISSUE THREAD

**Issue by ZakaShad** [ZakaShad/COMP-3005-F23-FP#3]

**Comment by ZakaShad** [comment]
- Learn about Swagger
- Connecting Swagger with NodeJS
- Using Swagger to automatically create API endpoint documentation

**Comment by Aranesh22** [comment]
https://docs.google.com/document/d/1OcWOFqyVy6Z7XuhAMpiaITmJpC-rsITnVNkppEw9NXY/edit?usp=sharing  

Need to add more info 
But tutorial links are there to explain 
maybe a README type file to explain it better
